version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1884:1883"  # mapear puerto 1883 del contenedor al 1884 del host (tu simulador usa 1884)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
    networks:
      - solar_net

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - solar_net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - solar_net

  ingestor:
    build: ./ingestor
    container_name: ingestor
    depends_on:
      timescaledb:
        condition: service_healthy
      mosquitto:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/postgres
    restart: unless-stopped
    networks:
      - solar_net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
      ingestor:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@timescaledb:5432/postgres
    restart: unless-stopped
    networks:
      - solar_net

volumes:
  mosquitto_data: {}
  timescaledb_data: {}
  redis_data: {}

networks:
  solar_net:
    driver: bridge