services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: project-timescaledb-1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: iot
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: project-redis-1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: project-mosquitto-1
    ports:
      - "1884:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    command: mosquitto -c /mosquitto-no-auth.conf

volumes:
  timescaledb_data:
  redis_data:
  mosquitto_data:
  mosquitto_logs: